name: Minaverse Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_and_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_ERROR_REPORTING_URL: ${{ vars.NEXT_PUBLIC_ERROR_REPORTING_URL }}
      NEXT_PUBLIC_ERROR_REPORTING_APP_ID: ${{ vars.NEXT_PUBLIC_ERROR_REPORTING_APP_ID }}
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Build app
      run: pnpm build
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps chromium
    - name: Run Playwright tests
      run: pnpm test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
